-- Tabla para almacenar los tipos de reacciones disponibles
CREATE TABLE apex_reactions (
    reaction_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    reaction_code VARCHAR2(50) NOT NULL,
    reaction_title VARCHAR2(100) NOT NULL,
    icon_name VARCHAR2(50) NOT NULL,
    display_order NUMBER DEFAULT 1 NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT apex_reactions_pk PRIMARY KEY (reaction_id),
    CONSTRAINT apex_reactions_code_uk UNIQUE (reaction_code),
    CONSTRAINT apex_reactions_is_active_chk CHECK (is_active IN ('Y', 'N'))
);


-- Comentarios de las columnas
COMMENT ON TABLE apex_reactions IS 'Tabla para almacenar los tipos de reacciones disponibles en la aplicación';
COMMENT ON COLUMN apex_reactions.reaction_id IS 'Identificador único de la reacción';
COMMENT ON COLUMN apex_reactions.reaction_code IS 'Código único para identificar la reacción (para uso en CSS/JS)';
COMMENT ON COLUMN apex_reactions.reaction_title IS 'Título descriptivo de la reacción que se mostrará como tooltip';
COMMENT ON COLUMN apex_reactions.icon_name IS 'Emoji o símbolo que representa la reacción';
COMMENT ON COLUMN apex_reactions.display_order IS 'Orden de visualización en el panel de reacciones';
COMMENT ON COLUMN apex_reactions.is_active IS 'Indica si la reacción está activa (Y) o inactiva (N)';

/

BEGIN
    -- DELETE FROM apex_user_reactions;
    -- DELETE FROM apex_reactions;

    -- Insertar reacciones predefinidas con iconos APEX
    INSERT INTO apex_reactions (reaction_code, reaction_title, icon_name, display_order)
    VALUES ('like', 'Like', 'fa-thumbs-up', 1);

    INSERT INTO apex_reactions (reaction_code, reaction_title, icon_name, display_order)
    VALUES ('celebrate', 'Celebrate', 'fa-trophy', 2);

    INSERT INTO apex_reactions (reaction_code, reaction_title, icon_name, display_order)
    VALUES ('support', 'Support', 'fa-heart', 3);

    INSERT INTO apex_reactions (reaction_code, reaction_title, icon_name, display_order)
    VALUES ('love', 'Love', 'fa-star', 4);

    INSERT INTO apex_reactions (reaction_code, reaction_title, icon_name, display_order)
    VALUES ('insightful', 'Insightful', 'fa-lightbulb-o', 5);

    INSERT INTO apex_reactions (reaction_code, reaction_title, icon_name, display_order)
    VALUES ('curious', 'Curious', 'fa-question-circle', 6);

    COMMIT;
END;
/