-- Core Unique Names Table
-- Version: 1.0
-- Description: Generic table to manage unique names for any entity type

create table core_unique_names (
    name_id                      number generated by default on null as identity (start with 1) primary key not null
  , entity_type                  varchar2(50 char) not null
  , base_name                    varchar2(100 char) not null
  , counter                      number default 0 not null
  , last_used                    timestamp with local time zone default localtimestamp not null
  , active_yn                    varchar2(1 char) default 'Y' not null
  , created_by                   varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                   timestamp with local time zone default localtimestamp not null
  , last_updated_by              varchar2(60 char)
  , last_updated_on              timestamp with local time zone
  , constraint uk_core_unique_names_entity_base unique (entity_type, base_name)
  , constraint chk_core_unique_names_active_yn check (active_yn in ('Y', 'N'))
);

-- column comments
begin
  execute immediate 'comment on column core_unique_names.name_id is ''Unique identifier for the name record (Primary Key).''';
  execute immediate 'comment on column core_unique_names.entity_type is ''Type of entity (USER, PROJECT, TENANT, etc.).''';
  execute immediate 'comment on column core_unique_names.base_name is ''Base name without numbers (e.g., john.doe, project-alpha).''';
  execute immediate 'comment on column core_unique_names.counter is ''Current counter for this base name.''';
  execute immediate 'comment on column core_unique_names.last_used is ''Timestamp when this name was last used.''';
  execute immediate 'comment on column core_unique_names.active_yn is ''Indicates if the name record is active (Y) or not (N).''';
  execute immediate 'comment on column core_unique_names.created_by is ''User who created the record.''';
  execute immediate 'comment on column core_unique_names.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column core_unique_names.last_updated_by is ''User who last updated the record.''';
  execute immediate 'comment on column core_unique_names.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table core_unique_names is ''Generic table to manage unique names for any entity type with automatic numbering for duplicates.''';
end;
/

create or replace trigger core_unique_names_bu_trg
before update
on core_unique_names
referencing old as old new as new
for each row
begin
  :new.last_updated_on := localtimestamp;
  :new.last_updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
