-- Core Users Table
-- Version: 1.0
-- Description: System users with automatic unique username generation

create table core_users (
    user_id                     number generated by default on null as identity (start with 1) primary key not null
  , username                    varchar2(100 char) not null
  , email                       varchar2(200 char) not null
  , first_name                  varchar2(100 char) not null
  , last_name                   varchar2(100 char) not null
  , display_name                varchar2(200 char)
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint uk_core_users_username unique (username)
  , constraint uk_core_users_email unique (email)
  , constraint chk_core_users_active_yn check (active_yn in ('Y', 'N'))
);

-- Comments
comment on table core_users is 'System users with automatic unique username generation';
comment on column core_users.username is 'Unique username generated automatically';
comment on column core_users.email is 'Unique email address';

-- Audit trigger
create or replace trigger core_users_bu_trg
before update
on core_users
referencing old as old new as new
for each row
begin
  :new.last_updated_on := localtimestamp;
  :new.last_updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/ 