-- TaskFlow Navigation Menu Table
-- Version: 1.0
-- Description: Dynamic navigation menu for TaskFlow system
drop table core_navigation_menu purge;

create table core_navigation_menu (
    id                          number generated by default on null as identity (start with 1) primary key not null
  , parent_id                   number -- For hierarchical menus
  , menu_name                   varchar2(200 char) not null
  , menu_label                  varchar2(200 char) not null -- Text displayed in menu
  , menu_level                  number default 1 -- Hierarchical level
  , app_id                      number -- APEX Application ID (10000, 10200, 10300, etc.)
  , target_page                 number -- APEX page number
  , target_url                  varchar2(500 char) -- Custom URL (alternative to page)
  , sort_order                  number default 0 -- Display order
  , icon_class                  varchar2(100 char) -- CSS icon class (fa-home, etc.)
  , image_attributes            varchar2(200 char) -- width, height, etc.
  , image_alt_text              varchar2(200 char) -- Alt text for accessibility
  , is_current                  varchar2(1 char) -- Y, NO, NULL (for dynamic current detection)
  , active_yn                   varchar2(1 char) default 'Y' not null
  , created_by                  varchar2(60 char) default
                                  coalesce(
                                    sys_context('APEX$SESSION','app_user')
                                  , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                                  , sys_context('userenv','session_user')
                                  )
                                  not null
  , created_on                  timestamp with local time zone default localtimestamp not null
  , last_updated_by             varchar2(60 char)
  , last_updated_on             timestamp with local time zone
  , constraint fk_core_navigation_menu_parent foreign key (parent_id) references core_navigation_menu(id)
  , constraint uk_core_navigation_menu_name unique (menu_name)
  , constraint chk_core_navigation_menu_current check (is_current in ('Y', 'N'))
  , constraint chk_core_navigation_menu_active_yn check (active_yn in ('Y', 'N'))
);

-- column comments
begin
  execute immediate 'comment on column core_navigation_menu.id is ''Unique identifier for the navigation menu item (Primary Key).''';
  execute immediate 'comment on column core_navigation_menu.parent_id is ''References the parent menu item for hierarchical menus.''';
  execute immediate 'comment on column core_navigation_menu.menu_name is ''Internal name for the menu item.''';
  execute immediate 'comment on column core_navigation_menu.menu_label is ''Text displayed in the navigation menu.''';
  execute immediate 'comment on column core_navigation_menu.app_id is ''APEX Application ID (10000, 10200, 10300, etc.).''';
  execute immediate 'comment on column core_navigation_menu.target_page is ''APEX page number to navigate to.''';
  execute immediate 'comment on column core_navigation_menu.target_url is ''Custom URL (alternative to page number).''';
  execute immediate 'comment on column core_navigation_menu.menu_level is ''Hierarchical level (1=root, 2=submenu, etc.).''';
  execute immediate 'comment on column core_navigation_menu.sort_order is ''Display order within the same level.''';
  execute immediate 'comment on column core_navigation_menu.icon_class is ''CSS icon class (e.g., fa-home, fa-user).''';
  execute immediate 'comment on column core_navigation_menu.image_attributes is ''Image attributes (width, height, etc.).''';
  execute immediate 'comment on column core_navigation_menu.image_alt_text is ''Alt text for accessibility.''';
  execute immediate 'comment on column core_navigation_menu.is_current is ''Y=always current, N=never current, NULL=dynamic detection.''';
  execute immediate 'comment on column core_navigation_menu.active_yn is ''Indicates if the menu item is active (Y) or not (N).''';
  execute immediate 'comment on column core_navigation_menu.created_by is ''User who created the record (user_name from users table).''';
  execute immediate 'comment on column core_navigation_menu.created_on is ''Timestamp when the record was created.''';
  execute immediate 'comment on column core_navigation_menu.last_updated_by is ''User who last updated the record (user_name from users table).''';
  execute immediate 'comment on column core_navigation_menu.last_updated_on is ''Timestamp when the record was last updated.''';

  -- table comment
  execute immediate 'comment on table core_navigation_menu is ''Dynamic navigation menu for TaskFlow system.''';
end;
/

create or replace trigger core_navigation_menu_bu_trg
before update
on core_navigation_menu
referencing old as old new as new
for each row
begin
  :new.last_updated_on := localtimestamp;
  :new.last_updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/ 