create table html_documents (
    id                          number generated by default on null as identity (start with 1) primary key not null,
  , document_name               varchar2(200 char)   not null
  , html_content                clob                 not null
  , active_yn                   char(1)              default 'Y' not null
  , constraint chk_html_docs_active_yn check (active_yn in ('Y','N'))
);

-- Column comments
comment on column html_documents.id is 'Unique identifier for the HTML document.';
comment on column html_documents.document_name is 'Name of the HTML document for reference.';
comment on column html_documents.html_content is 'The actual HTML content stored as CLOB.';
comment on column html_documents.active_yn is 'Flag to indicate if the document is active (Y/N).';

-- Table comment
comment on table html_documents is 'Stores HTML documents that can be downloaded as PDF files through APEX.';