-- Crear la tabla para almacenar datos jerárquicos
CREATE TABLE demo_hierarchical_data (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id         NUMBER,
    nombre            VARCHAR2(100) NOT NULL,
    descripcion       VARCHAR2(4000),
    tipo              VARCHAR2(50),
    fecha_creacion    DATE DEFAULT SYSDATE,
    estado            VARCHAR2(20) DEFAULT 'ACTIVO',
    orden             NUMBER,
    creado_por        VARCHAR2(50) DEFAULT USER,
    
    -- Restricciones
    CONSTRAINT demo_hier_parent_fk FOREIGN KEY (parent_id) 
        REFERENCES demo_hierarchical_data(id) ON DELETE CASCADE,
    CONSTRAINT demo_hier_check_estado 
        CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE INDEX demo_hier_parent_idx ON demo_hierarchical_data(parent_id);
CREATE SEQUENCE demo_hier_seq START WITH 100 INCREMENT BY 1;